services:
  emulator:
    build:
      context: ./emulator
      dockerfile: Dockerfile
      args:
        - FIREBASE_VERSION=13.3.0
    stop_grace_period: 1m
    environment:
      FIREBASE_AUTH_EMULATOR_HOST: "localhost:9099"
      FIRESTORE_EMULATOR_HOST: "localhost:5050"
      PUBSUB_EMULATOR_HOST: "localhost:8085"
      FUNCTIONS_EMULATOR_HOST: "localhost:5001"
      FIREBASE_PROJECT: "hc-show-calendar"
      GCLOUD_PROJECT: "hc-show-calendar"
      FORCE_COLOR: 'true'
      DATA_DIRECTORY: "data"
      CHOKIDAR_USEPOLLING: 'true'
    ports:
      - "4000:4001" # ui
      - "4400:4401" # hub
      - "4600:4601" # logging
      - "5001:5002" # functions
      - "5050:8081" # firestore
      - "8085:8086" # pubsub
      - "9000:9001" # database
      - "9099:9100" # auth
      - "9199:9200" # Storage
      - "6000:6001" # Hosting
    volumes:
      - ./firebase:/srv/firebase:rw
      - ./cache:/root/.cache/:rw
      - ~/.config/:/root/.config
      - ./firebase/data:/srv/firebase/data:rw

  hc-shows-calendar-back:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GCP_PROJECT_ID: "hc-show-calendar"
      FIRESTORE_EMULATOR_HOST: "localhost:5050"
    ports:
      - "8080:8080"
