services:
  firebase-emulator:
    container_name: firebase-emulator
    image: evolutecx/firebase-emulator:latest
    restart: always
    environment:
      FB_PROJECT_ID: "hc-show-calendar"
    ports:
      - 8080:8080 #firestore
      - 4000:4000 #emulator ui
      - 9099:9099 #fb auth
      - 9199:9199 #fb cloud storage
      - 9000:9000 #fb realtime db
    volumes:
      - ./firebase-data:/firebase/data:rw #stores data on shutdown to ./firebase-data/data/export on your host

  hc-shows-calendar-back:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - firebase-emulator
    environment:
      GCP_PROJECT_ID: "hc-show-calendar"
      FIRESTORE_EMULATOR_HOST: "firebase-emulator:8080"
      APPLICATION_PORT: "9090"
      ALLOWED_ORIGINS: "*"
    ports:
      - "9090:9090"
